name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Debug Directory Structure
      run: |
        echo "Current directory: $(pwd)"
        ls -la
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build || echo "Build step may have failed but continuing"
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug || echo "APK build step may have failed but continuing"
      
    - name: Debug APK Output Directory
      run: |
        echo "Checking APK output directory:"
        ls -la app/build/outputs || echo "Directory not found"
        ls -la app/build/outputs/apk || echo "Directory not found"
        ls -la app/build/outputs/apk/debug || echo "Directory not found"
        find . -name "*.apk" || echo "No APK files found" 