name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for proper versioning
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    # Improved caching strategy
    - name: Cache Gradle Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.android/build-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    # Auto-versioning setup
    - name: Set up Version Code
      id: version-code
      run: |
        # Use GitHub Run ID for version code to ensure it's always increasing
        VERSION_CODE=${{ github.run_number }}
        # Add short SHA as a version name suffix
        SHORT_SHA=$(git rev-parse --short HEAD)
        VERSION_NAME="1.0.0-$SHORT_SHA"
        echo "Generated Version Code: $VERSION_CODE"
        echo "Generated Version Name: $VERSION_NAME"
        echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
        echo "::set-output name=version_code::$VERSION_CODE"
        echo "::set-output name=version_name::$VERSION_NAME"
        
    - name: Setup Gradle
      run: |
        # Make gradlew executable
        if [ -f "./gradlew" ]; then
          chmod +x ./gradlew
        else
          echo "No gradlew file found in root directory"
          find . -name "gradlew" -type f -exec chmod +x {} \;
        fi
        
    - name: Build Debug APK
      run: |
        # Apply version code and name if gradlew exists in root
        if [ -f "./gradlew" ]; then
          ./gradlew assembleDebug \
          --no-daemon \
          --stacktrace \
          -PversionCode=${{ env.VERSION_CODE }} \
          -PversionName=${{ env.VERSION_NAME }}
        else
          # Try to find gradlew in subdirectories
          GRADLEW_PATH=$(find . -name "gradlew" -type f | head -n 1)
          if [ -n "$GRADLEW_PATH" ]; then
            echo "Using gradlew at: $GRADLEW_PATH"
            $GRADLEW_PATH assembleDebug \
            --no-daemon \
            --stacktrace \
            -PversionCode=${{ env.VERSION_CODE }} \
            -PversionName=${{ env.VERSION_NAME }}
          else
            echo "Failed to find gradlew file"
            exit 1
          fi
        fi
    
    - name: Find APK
      id: find-apk
      run: |
        # Find all generated APK files
        APK_FILES=$(find . -name "*.apk" -type f)
        if [ -z "$APK_FILES" ]; then
          echo "No APK files found!"
          exit 1
        fi
        
        # Use the most recently modified APK
        LATEST_APK=$(ls -t $APK_FILES | head -n 1)
        echo "Found APK: $LATEST_APK"
        echo "APK_PATH=$LATEST_APK" >> $GITHUB_ENV
        echo "::set-output name=apk_path::$LATEST_APK"
        
        # Extract APK filename
        APK_FILENAME=$(basename "$LATEST_APK")
        echo "APK_FILENAME=$APK_FILENAME" >> $GITHUB_ENV
        echo "::set-output name=apk_filename::$APK_FILENAME"

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-${{ env.VERSION_NAME }}
        path: ${{ env.APK_PATH }}
        
    # Create GitHub Release for tagged commits
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.APK_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 